In [98]:
import numpy as np
array=np.ones((1000,5000),np.uint64)
list1=[1,2,4,5,6]
arr=np.array(list1)
arr1=np.array([[1,2,3,4,7,2],[6,7,4,2,8,9],[1,2,3,4,7,2],[6,7,4,2,8,9]],np.float64)
print(arr1.dtype) or print(arr1.dtype.name) # checking Data Type
print(arr1.size) # checking total Element in Arrays
print(arr1.itemsize) # Size of Each Element
print(arr1.size*arr1.itemsize) #checking total size of array in memory(byte)
print(arr1.shape) # checkin shape(rows,colums)
print(arr1) #shwoing array with values
print(arr1.ndim) #dimensions(rows and colums avail=2,if single rows or colums=1)


float64
float64
24
8
192
(4, 6)
[[1. 2. 3. 4. 7. 2.]
 [6. 7. 4. 2. 8. 9.]
 [1. 2. 3. 4. 7. 2.]
 [6. 7. 4. 2. 8. 9.]]
2
