In [77]:
import numpy as np
import matplotlib.pyplot as plt
A=np.ones((5,5))
B=5.0*np.ones((5,5))
print(A-B)
print(A+B)
print(A*B)
print(A/B)
A1=B**2
print(np.sqrt(B))
print(np.power(B,2))
print(np.exp(B))
print(B.T) #Transpose
I=np.identity(10)
np.dot(A,I)
inv=np.linalg.inv(A)
C=np.random.randint(-5,5,(5,5))
inv=np.linalg.inv(C)
quad=-4+np.sqrt(4**2-2*2*4)/2
eigval,eigvec=np.linalg.eig(A)

[[-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]
[[2.23606798 2.23606798 2.23606798 2.23606798 2.23606798]
 [2.23606798 2.23606798 2.23606798 2.23606798 2.23606798]
 [2.23606798 2.23606798 2.23606798 2.23606798 2.23606798]
 [2.23606798 2.23606798 2.23606798 2.23606798 2.23606798]
 [2.23606798 2.23606798 2.23606798 2.23606798 2.23606798]]
[[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]]
[[148.4131591 148.4131591 148.4131591 148.4131591 148.4131591]
 [148.4131591 148.4131591 148.4131591 148.4131591 148.4131591]
 [148.4131591 148.4131591 148.4131591 148.4131591 148

ValueError: shapes (5,5) and (10,10) not aligned: 5 (dim 1) != 10 (dim 0)